steps:
  - label: ":rocket: Launch Pipeline!"
    plugins:
      - hasura/smooth-checkout#v4.4.1:
          repos:
            - config:
                - url: "https://github.com/SciML/SciMLDocs.git"
                  ref: "${BUILDKITE_COMMIT}"
                  clone_flags: "--depth=1"
      - staticfloat/cryptic#v2:
          signed_pipelines:
            - pipeline: .buildkite/aggregate.yml
              signature_file: .buildkite/aggregate.yml.signature
          unsigned_pipelines:
            - .buildkite/documentation.yml

    command: "true"
    agents:
      queue: "juliaecosystem"
      sandbox_capable: true
      cryptic_capable: true
